// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB2FWBicmLVkq0_esZlFFxhikG6sSLL5E',
    appId: '1:557264628963:web:605d2621302a2653dfe9d6',
    messagingSenderId: '557264628963',
    projectId: 'eventflow-team-proj',
    authDomain: 'eventflow-team-proj.firebaseapp.com',
    storageBucket: 'eventflow-team-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqq1GvMyPqnqBv2lvrGaDgH2RHxBUhDw8',
    appId: '1:557264628963:android:cfc1bda60d041bfedfe9d6',
    messagingSenderId: '557264628963',
    projectId: 'eventflow-team-proj',
    storageBucket: 'eventflow-team-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjUa2DWitfl3s62ICzYD3kc90gBjmHjww',
    appId: '1:557264628963:ios:be2a575180f6717edfe9d6',
    messagingSenderId: '557264628963',
    projectId: 'eventflow-team-proj',
    storageBucket: 'eventflow-team-proj.appspot.com',
    iosBundleId: 'com.example.eventflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjUa2DWitfl3s62ICzYD3kc90gBjmHjww',
    appId: '1:557264628963:ios:0f5f6a085d391f65dfe9d6',
    messagingSenderId: '557264628963',
    projectId: 'eventflow-team-proj',
    storageBucket: 'eventflow-team-proj.appspot.com',
    iosBundleId: 'com.example.eventflow.RunnerTests',
  );
}
